apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deploy
  labels:
    app: nginx-lb
spec:
  template:
    metadata:
      name: my-ngnix-pod
      labels:
        app: ngnix-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 2
  selector:
    matchLabels:
      app: ngnix-pod

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
  selector:
    matchLabels:
      app: ngnix-pod