apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ngnix-deploy
  labels:
    name: ngnix-cip
spec:
  template:
    metadata:
      name: my-ngnix-pod
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod
---

apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  type: ClusterIP
  ports:
  - targetPort: 80
    port: 80
  selector:
    app: nginx-pod